# Generated by Django 3.1.5 on 2021-04-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('aadhar', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('medications', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ESD_SEM4_DB',
            },
        ),
    ]
