# Generated by Django 3.1.5 on 2021-04-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
