# Generated by Django 3.1.5 on 2021-04-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210404_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
