# Generated by Django 3.1.5 on 2021-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=50)),
                ('vaccine', models.CharField(max_length=50)),
                ('time', models.TimeField(max_length=50)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
