# Generated by Django 3.1.5 on 2021-04-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vaccine',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
