# Generated by Django 3.1.5 on 2021-04-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210410_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='phone',
            new_name='location',
        ),
    ]
